#!/usr/bin/env bash
# This script will display numbers from 1 to 100, applying the FizzBuzz rules when necessary.

for ((number=1; number<=100; number++))
do
    if ((number % 3 == 0)) && ((number % 5 == 0)); then
        echo "FizzBuzz"
    elif ((number % 3 == 0)); then
        echo "Fizz"
    elif ((number % 5 == 0)); then
        echo "Buzz"
    else
        echo "$number"
    fi
done
