#!/usr/bin/bash
# Displaying the content of the file /etc/passwd
while IFS=: read -r username password userid groupid comment homedirectory command
do
    echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $command shell. User ID's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
