#!/usr/bin/env bash
# This is a Bash script to display the content of the file /etc/passwd using a while loop and IFS.

# Set IFS (Internal Field Separator) to ":" delimiter
IFS=":"

# Read the /etc/passwd file line by line
while read -r username password user_id group_id user_info home_directory command_shell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command_shell. User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

# Reset IFS to its default value
IFS=$' \t\n'
