#!/usr/bin/env bash

# This is a Bash script that loops from 1 to 10 and displays different messages based on the loop iteration.

i=1

while [ $i -le 10 ]
do
  if [ $i -eq 4 ]; then
    echo "Bad luck"
  elif [ $i -eq 8 ]; then
    echo "Good luck"
  else
    echo "Best School"
  fi

  i=$((i+1))
done


