#!/usr/bin/env bash
# Script to display numbers from 1 to 20 with specific messages for certain iterations

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    counter=$((counter + 1))
done
