#!/usr/bin/env bash
#nested loop stuff

hours=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour $hours"
    ((hours++))
     while [ $minutes -ne 60 ]
      do
         echo $minites
         ((minites++))
    done
   ((minites=1))
   done
