#!/usr/bin/env bash
# This script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not hidden
    if [[ "$file" != .* ]]; then
        name=${file#*-}  # remove everything before the first dash
        echo "$name"
    fi
done
