#!/usr/bin/env bash
# Display a list of currently running processes

# Use the ps command to get information about the processes
# Use the -e flag to show processes for all users
# Use the -o flag to specify the format of the output
# Use the h option to exclude the header line from the output
# Use the --forest option to show the process
