#!/usr/bin/env bash
# Bash script to display a list of currently running processes, including process hierarchy

# Use the ps command with options to show all processes, for all users, including those without a TTY
# Format the output with headers
# Use the --forest option to display the process hierarchy
ps auxf | head -1
ps auxf | tail -n +2 | sort -rn -k4

# End of the script
