#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"

for pid in /proc/*/; do
    pid=${pid%/}
    process_name=$(<"${pid}/comm")
    
    if [[ $process_name == "bash" ]]; then
        echo "$pid $process_name"
    fi
done
