#!/usr/bin/env bash

# This script stops the 4-to_infinity_and_beyond process

# Find the process ID (PID) of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Send an interrupt signal to the process
kill -SIGINT $pid

# Wait for the process to terminate
wait $pid

echo "Process 4-to_infinity_and_beyond has been terminated."
