#!/usr/bin/env bash
#dont stop me

# Get the process ID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process ID is valid
if [[ -n "$pid" ]]; then
    # Terminate the process using kill command
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi

Save the above script in a file named "stop_4_to_infinity_and_beyond.sh". Then, you can run the script in terminal #1 by typing "./stop_4_to_infinity_and_beyond.sh". This will terminate the 4-to_infinity_and_beyond process running in terminal #0.
